services:

  backend:
    build: backend
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend
      - ./emergency_support.db:/app/emergency_support.db
    ports:
      - 5000:5000
    env_file:
      - project.env
    #depends_on:
    #  - database

  client:
    build: client_r
    restart: unless-stopped
    volumes:
      - ./client_r:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
  