services:
  # Backend - dev mode, exposed for browser access
  backend:
    build: backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    env_file:
      - project.env
    ports:
      - 5000:5000

  # Frontend apps - production mode, accessible from browser
  consumer-app:
    build: consumer-app
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

  legal-entity-consumer-app:
    build: legal-entity-consumer-app
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
