CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  done BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE generators (
  id SERIAL PRIMARY KEY,
  location VARCHAR(255) NOT NULL,
  inuse BOOLEAN NOT NULL DEFAULT true
)